Track2012/Track/Controllers/GhostController.cs
using System;
using System.Linq;
using System.Threading;
using System.Web.Mvc;
using Track.Controllers.Abstract;
using Track.Domain.Enums;
using Track.Domain.Interfaces;
using Track.Domain.Services;

namespace Track.Controllers
{
    public class GhostController : BaseController
    {
        public IGhostService GhostService { get; set; }
        public ICacheService CacheService { get; set; }

        public ActionResult DailySpendLoad()
        {
            var entries = RSTRepository.GetAllGhostEntries();
            foreach (int id in entries)
            {
                var entry = RSTRepository.GetGhostEntry(id);
                if (entry != null)
                {
                    GhostService.ProcessGhostQueueItem(entry);
                }
            }
            return new EmptyResult();
        }

        public ActionResult PollAccount(int id)
        {
            var entry = RSTRepository.GetGhostEntry(id);
            if (entry != null)
            {
                GhostService.ProcessGhostQueueItem(entry);
            }
            return new EmptyResult();
        }

        public ActionResult LoadGhost(int spendAccountId, DateTime startDate, DateTime endDate)
        {
            var ghostEntry = RSTRepository.GetGhostQueueForSpendAccount(spendAccountId);

            var loopDate = startDate;
            if (ghostEntry != null && ghostEntry.GhostQueue.Count > 0)
            {
                while (loopDate <= endDate)
                {
                    GhostService.ProcessItem(ghostEntry.GhostQueue.First(), loopDate);
                    Thread.Sleep(3000);
                    loopDate = loopDate.AddDays(1);

                    //Wait 5 seconds between date loads
                    if (loopDate <= endDate)
                        Thread.Sleep(5000);
                }
            }


            return new EmptyResult();
        }

        public ActionResult SendDailyStatus()
        {
            RSTRepository.SendDailyStatusEmail();
            return new EmptyResult();
        }

    }
}

Track2012/Track/Views/Ghost/GhostLog.cshtml
@model IEnumerable<GhostLog>

<table id="ghostlog-table" class="ui-table" dt-filter="false" dt-sort="false">
    <tr>
        <th>TimeStamp</th>
        <th>Message</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.TimeStamp)</td>
        <td>@Html.DisplayFor(modelItem => item.Message)</td>
    </tr>
}

</table>

Track2012/Track/Views/Ghost/GhostQueue.cshtml
@model GhostQueueViewModel
<table id="ghostqueue-table" class="ui-table" dt-filter="false" dt-sort="false">
    <thead>
        <tr>
            <th>Added</th>
            <th>Run</th>
            <th>Sent</th>
            <th>Fulfilled</th>
            <th>Errors</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.GhostQueue)
        {
            <tr>
                <!-- TODO: figure out why data annotations aren't working [GhostQueueMeta]-->
                <td>@Html.DisplayFor(modelItem => item.AddedToQueue)</td>
                <td>@Html.DisplayFor(modelItem => item.QueuedUTCDateTime)</td>
                <td>@Html.DisplayFor(modelItem => item.RequestSent)</td>
                <td>@Html.DisplayFor(modelItem => item.RequestFulfilled)</td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestError) 
                    @if (item.RequestError)
                    {
                        @Html.ActionLink("View", "GhostLog", "Ghost", new { id = item.SpendAccountId }, new { @class = "popup-dialog", title = "Ghost Error Log", dialogWidth = 700 })
                    }
                </td>
            </tr>
        }
    </tbody>

</table>

Track2012/Track/Views/Ghost/SpendSuccess.cshtml
@{
    ViewBag.Title = "Success Message";
}

<h2>Spend Loaded Successfully for yesterday.</h2>